### ISSUE TITLE
"ENSIME ready" message appears multiple times

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-emacs#215]
and emacs slows to a crawl. This only happens sometimes, and sometimes goes away by itself.

**Comment by fommil** [comment]
hmm, that sounds weird. have you got an example project that exhibits the problem?

I'd recommend clearing your caches and updating all the things first.

**Comment by rorygraves** [comment]
@fommil - this isn't something weird like the Analyser crashing and being restarted by Akka?  - random thought.

**Comment by rorygraves** [comment]
@greenrd Can you paste a log fragement of the server log?

**Comment by greenrd** [comment]
It happened immediately after I visited a new file:

```
10:55:08.036 ERROR akka://ENSIME/user/project/analyzer a.a.OneForOneStrategy - requirement failed: SourceFileInfo(/home/robin/git/censored.scala,None,None) does not exist
java.lang.IllegalArgumentException: requirement failed: SourceFileInfo(/home/robin/git/censored.scala,None,None) does not exist
	at scala.Predef$.require(Predef.scala:219) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.Analyzer$$anonfun$handleReloadFiles$1.apply(Analyzer.scala:268) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$handleReloadFiles$1.apply(Analyzer.scala:267) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.Analyzer.handleReloadFiles(Analyzer.scala:267) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:172) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.Analyzer$$anonfun$allTheThings$1.applyOrElse(Analyzer.scala:151) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.Analyzer$$anonfun$ready$1.applyOrElse(Analyzer.scala:148) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.12.jar:na]
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:na]
	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
	at org.ensime.core.Analyzer.aroundReceive(Analyzer.scala:40) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
10:55:08.071 DEBUG akka://ENSIME/user/$b/handler/267 o.e.s.RequestHandler - SymbolDesignationsReq(/home/robin/git/censored.scala,0,0,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSymbol, TraitSymbol, ObjectS
10:55:08.071 DEBUG akka://ENSIME/user/project o.e.c.Project - received handled message SymbolDesignationsReq(/home/robin/git/censored.scala,0,0,List(VarSymbol, ValSymbol, VarFieldSymbol, ValFieldSymbol, FunctionCallSymbol, OperatorFieldSymbol, ParamSymbol, ClassSym
10:55:09.505 DEBUG akka://ENSIME/user/$b/handler o.e.s.ConnectionHandler - received handled message SendBackgroundMessageEvent(Initializing Analyzer. Please wait...,105)
```

and then it gets in a loop in which such messages are displayed over and over.

**Comment by fommil** [comment]
that "visiting a new file" thing is a known defect, but it should be harmless -- the exception goes away once you save the file. Is this sending the ENSIME ready message?

This sounds like a server bug.

**Comment by fommil** [comment]
heh, you actually reported this https://github.com/ensime/ensime-server/issues/930

is it the same thing or are you seeing something extra?

**Comment by greenrd** [comment]
It is basically the same thing except that it sends the ENSIME ready message and generally locks up emacs temporarily every few seconds.

**Comment by fommil** [comment]
does it fix itself when you save the file?

Let's just track this on the server side.

**Comment by greenrd** [comment]
Yes, it does.

**Comment by fommil** [comment]
If you want to avoid the problem in the meantime you could add a `find-file` hook to save new scala buffers to file as soon as you create them. But I suspect rory will fix this very soon.
