### ISSUE TITLE
C-c C-d i stop the ensime server

### ISSUE THREAD

**Issue by gavinsun2008** [ensime/ensime-emacs#221]
Hi, 

I use emacs + ensime for scala programming. When I debug the simple HelloWorld program, if I use the command C-c C-d i to inspect one variable, the project will break the connection to the server. 
If I run M-x ensime again, the Emacs will dying with no response, so I must kill it with kill -9.

My environment is :
GNU Emacs 24.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.10.7)
ensime             20150818.528 installed  ENhanced Scala Interaction Mode for Emacs

The error message is 
[Server connection closed unexpectedly: connection broken by remote peer
 byte-code: Lisp connection closed unexpectedly]

I find the following error log in *inferior-ensime-server-root* buffer:
16:05:09.462 ERROR akka://ENSIME/user/ensime-main/project/debugging o.e.c.DebugManager - Exception thrown whilst handling vm action
com.sun.jdi.AbsentInformationException: null
	at com.sun.tools.jdi.ConcreteMethodImpl.getVariables1(ConcreteMethodImpl.java:495) ~[tools.jar:na]
	at com.sun.tools.jdi.ConcreteMethodImpl.getVariables(ConcreteMethodImpl.java:540) ~[tools.jar:na]
	at com.sun.tools.jdi.ConcreteMethodImpl.variables(ConcreteMethodImpl.java:217) ~[tools.jar:na]
	at com.sun.tools.jdi.StackFrameImpl.createVisibleVariables(StackFrameImpl.java:159) ~[tools.jar:na]
	at com.sun.tools.jdi.StackFrameImpl.visibleVariables(StackFrameImpl.java:182) ~[tools.jar:na]
	at org.ensime.core.DebugManager$VM.stackSlotForName(DebugManager.scala:838) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$VM.locationForName(DebugManager.scala:729) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$fromUser$1$$anonfun$applyOrElse$20.apply(DebugManager.scala:353) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$fromUser$1$$anonfun$applyOrElse$20.apply(DebugManager.scala:352) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$org$ensime$core$DebugManager$$handleRPCWithVMAndThread$2$$anonfun$apply$5.apply(DebugManager.scala:167) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$org$ensime$core$DebugManager$$handleRPCWithVMAndThread$2$$anonfun$apply$5.apply(DebugManager.scala:166) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.DebugManager$$anonfun$org$ensime$core$DebugManager$$handleRPCWithVMAndThread$2.apply(DebugManager.scala:166) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$org$ensime$core$DebugManager$$handleRPCWithVMAndThread$2.apply(DebugManager.scala:165) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$liftedTree1$1$1.apply(DebugManager.scala:141) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$liftedTree1$1$1.apply(DebugManager.scala:140) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.DebugManager.liftedTree1$1(DebugManager.scala:140) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager.withVM(DebugManager.scala:139) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager.org$ensime$core$DebugManager$$handleRPCWithVMAndThread(DebugManager.scala:165) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.core.DebugManager$$anonfun$fromUser$1.applyOrElse(DebugManager.scala:351) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.7.jar:na]
	at org.ensime.core.DebugManager$$anonfun$fromJvm$1.applyOrElse(DebugManager.scala:185) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167) ~[scala-library-2.11.7.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:62) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.event.LoggingReceive.apply(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.12.jar:na]
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123) ~[scala-library-2.11.7.jar:na]
	at akka.event.LoggingReceive.applyOrElse(LoggingReceive.scala:50) ~[akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
	at org.ensime.core.DebugManager.aroundReceive(DebugManager.scala:24) ~[core_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
16:05:09.463 WARN  akka://ENSIME/user/ensime-main/project/debugging o.e.c.DebugManager - Could not access debug VM
16:05:09.463 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/27 o.e.s.RequestHandler - received handled message FalseResponse in state receive
16:05:09.466 ERROR akka://ENSIME/user/ensime-main/tcp-server/con1 o.e.s.t.TCPConnectionActor - Error seen during message processing, closing client connection
org.ensime.server.protocol.swank.SwankRPCFormatException: Invalid rpc request (swank:debug-value nil)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:870) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:859) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SwankProtocol.decode(SwankProtocol.scala:14) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.repeatedDecode(TCPConnectionActor.scala:104) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.attemptProcess(TCPConnectionActor.scala:93) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor$$anonfun$incoming$1.applyOrElse(TCPConnectionActor.scala:45) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.7.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
	at org.ensime.server.tcp.TCPConnectionActor.aroundReceive(TCPConnectionActor.scala:15) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: org.ensime.sexp.DeserializationException: Unable to parse SexpNil
	at org.ensime.sexp.formats.package$.deserializationError(package.scala:5) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolCommon$TraitFormatAlt.read(SwankFormats.scala:63) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:39) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:33) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$68.read(SwankFormats.scala:663) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$68.read(SwankFormats.scala:657) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:847) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:795) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$42.apply(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$42.apply(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.7.jar:na]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	... 18 common frames omitted
16:05:09.470 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/2 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server/con1#1512531469]] terminated

**Comment by fommil** [comment]
we have a PR to rewrite the debugging manager in progress. Do you mind checking again after that has been merged to see if it fixes your problem?

BTW, when the ENSIME connection dies you should kill the ensime server. You can do this by going to the ENSIME server buffer and killing it.

**Comment by gavinsun2008** [comment]
Thanks for your reply.
Once the package upgrade, I will use the new version to check again. 
Expect the PR merged quickly. For now, I just not use the debug function.
