### ISSUE TITLE
invalid swank:import-suggestions request

### ISSUE THREAD

**Issue by gdrte** [ensime/ensime-emacs#230]
I've observed this while accidentally hitting the key combination C-c C-r t. The server is not crashed, M-x ensime will reconnect, but if this is repeated, it is crashing the emacs as well.

emacs: 24.5.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) 
OS : Linux                                                                                                                                                                                               
Java : Java HotSpot(TM) 64-Bit Server VM 25.45-b02, Java(TM) SE Runtime Environment 1.8.0_45-b14                                                                                                         
Scala : version 2.11.6                                                                                                                                                                                   
Ensime : 0.9.10-SNAPSHOT

**Comment by fommil** [comment]
I use this command about 100 times a day, and it has never crashed Emacs for me. You're going to have to come up with a project and recipe to reproduce this one I'm afraid, because it is far more likely that you've got a dodgy environment or build of Emacs. :-P

**Comment by gdrte** [comment]
Sure,  I will try this in my MBP.  If it is reproducible,  I will make available the project and steps to reproduce.  To be clear,  emacs ensime client will be disconnected only when the command is tried  on empty point/line. Otherwise this intellisense works like a charm.  ☺

**Comment by gdrte** [comment]
I just tried this on my MBP. The behavior is same. emacs ensime client connection is terminated when C-c C-r t is pressed on empty line/point.

Here are the logs from emacs.
 OS : Mac OS X
Java : Java HotSpot(TM) 64-Bit Server VM 25.45-b02, Java(TM) SE Runtime Environment 1.8.0_45-b14
  Scala : version 2.11.6
  Ensime : 0.9.10-SNAPSHOT
GNU Emacs 24.5.1 (x86_64-apple-darwin14.3.0, NS apple-appkit-1347.57) of 2015-04-30 on gdrs-MacBook-Pro.local


ENSIME server starting...
Connecting to Swank on port 55321..
Connected to ENSIME speaking protocol 0.8.17, please wait while the project is loaded.
Initializing Analyzer. Please wait...
ENSIME ready. CanBuildFrom[List[Dream], Reality, List[Reality]]
Saving file /Users/gdr/Projects/scala-projects/hello-scala/src/main/scala/Hello.scala...
Wrote /Users/gdr/Projects/scala-projects/hello-scala/src/main/scala/Hello.scala
Saving file /Users/gdr/Projects/scala-projects/hello-scala/src/main/scala/Hello.scala...
Wrote /Users/gdr/Projects/scala-projects/hello-scala/src/main/scala/Hello.scala
[yas] snippet expanded.
[yas] Snippet 0 exited.
Saving file /Users/gdr/Projects/scala-projects/hello-scala/src/main/scala/Hello.scala...
Wrote /Users/gdr/Projects/scala-projects/hello-scala/src/main/scala/Hello.scala
Server connection closed unexpectedly: connection broken by remote peer

byte-code: Lisp connection closed unexpectedly

and logs from inferior-ensime-server-hello-scala buffer

13:23:40.644 ERROR akka://ENSIME/user/ensime-main/tcp-server/con1 o.e.s.t.TCPConnectionActor - Error seen during message processing, closing client connection
org.ensime.server.protocol.swank.SwankRPCFormatException: Invalid rpc request (swank:import-suggestions "/Users/gdr/Projects/scala-projects/hello-scala/src/main/scala/Hello.scala" 159 (nil) 10)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:870) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:859) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SwankProtocol.decode(SwankProtocol.scala:14) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.repeatedDecode(TCPConnectionActor.scala:104) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.attemptProcess(TCPConnectionActor.scala:93) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor$$anonfun$incoming$1.applyOrElse(TCPConnectionActor.scala:45) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.6.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.12.jar:na]
	at org.ensime.server.tcp.TCPConnectionActor.aroundReceive(TCPConnectionActor.scala:15) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.12.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.12.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.12.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
Caused by: org.ensime.sexp.DeserializationException: Unable to parse SexpNil
	at org.ensime.sexp.formats.package$.deserializationError(package.scala:5) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.BasicFormats$StringFormat$.read(BasicFormats.scala:34) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.BasicFormats$StringFormat$.read(BasicFormats.scala:30) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.CollectionFormats$$anon$1$$anonfun$read$1.apply(CollectionFormats.scala:65) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.CollectionFormats$$anon$1$$anonfun$read$1.apply(CollectionFormats.scala:65) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.6.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245) ~[scala-library-2.11.6.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.6.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245) ~[scala-library-2.11.6.jar:na]
	at scala.collection.immutable.List.map(List.scala:285) ~[scala-library-2.11.6.jar:na]
	at org.ensime.sexp.formats.CollectionFormats$$anon$1.read(CollectionFormats.scala:65) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:39) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:33) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:39) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:33) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:39) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.formats.LowPriorityProductFormats$HListFormat$$anon$4.read(ProductFormats.scala:33) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$68.read(SwankFormats.scala:663) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$68.read(SwankFormats.scala:657) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:810) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:795) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$42.apply(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$42.apply(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.util.Try$.apply(Try.scala:191) ~[scala-library-2.11.6.jar:na]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	... 18 common frames omitted
13:23:40.649 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/2 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server/con1#-1921556338]] terminated


Please let me know if you want to look at the project I've tried. This is a simple hello-world scala program created with typesafe activator.

```scala
object Hello {
  def main(args: Array[String]): Unit = {
    println("Hello world")
    //Tried C-c C-r t here
  }
}

````

**Comment by fommil** [comment]
Please put the project on github and I'll take a closer look.

**Comment by fommil** [comment]
BTW, I can believe it will kill the connection (it's a new failure detection algorithm @rorygraves proposed), but crashing Emacs sounds very very wrong.

**Comment by gdrte** [comment]
Please find the project here
https://github.com/gdrte/hello-world-ensime

**Comment by fommil** [comment]
ok, this is a client side bug. The following request is created

```
(swank:import-suggestions "/path/to/Hello.scala" 90 (nil) 10)
```

which is invalid, it should be

```
(swank:import-suggestions "/path/to/Hello.scala" 90 nil 10)
```

**Comment by fommil** [comment]
actually, the request shouldn't be sent.

**Comment by fommil** [comment]
try again in the next MELPA update

**Comment by gdrte** [comment]
Thank you very much for the fix. It is rock solid now.
