### ISSUE TITLE
Shutdown fails

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-emacs#265]
There is a menu entry in the ENSIME menu called "Shutdown ENSIME server". However, it doesn't work.

This is in the log:

```
19:58:00.035 ERROR akka://ENSIME/user/ensime-main/tcp-server/con1 o.e.s.t.TCPConnectionActor - Error seen during message processing, closing client connection
org.ensime.server.protocol.swank.SwankRPCFormatException: Invalid rpc request (swank:shutdown-server)
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:870) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:859) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SwankProtocol.decode(SwankProtocol.scala:14) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.repeatedDecode(TCPConnectionActor.scala:106) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor.attemptProcess(TCPConnectionActor.scala:95) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.tcp.TCPConnectionActor$$anonfun$incoming$1.applyOrElse(TCPConnectionActor.scala:47) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.7.jar:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]
	at org.ensime.server.tcp.TCPConnectionActor.aroundReceive(TCPConnectionActor.scala:15) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]
Caused by: org.ensime.sexp.DeserializationException: Unable to parse SexpCons(SexpSymbol(swank:shutdown-server),SexpNil)
	at org.ensime.sexp.formats.package$.deserializationError(package.scala:5) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:852) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:795) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.Sexp.convertTo(Sexp.scala:19) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$42.apply(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$42.apply(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at scala.util.Try$.apply(Try.scala:192) ~[scala-library-2.11.7.jar:na]
	at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:864) ~[swank_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	... 18 common frames omitted
19:58:00.036 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/2 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server/con1#-1199350350]] terminated
```

And then if you try to start ensime again, really weird hijinks ensue, including emacs hanging and worse...

**Comment by fommil** [comment]
Yes, I actually had this in my plan to fix this week.

As a workaround (and this is exactly how it will be implemented) just open the buffer containing the server output, and kill the buffer.

If you send a PR to do this (it's only three lines) I'll probably merge immediately. I'm a bit distracted with the Java PR (woot!).

**Comment by fommil** [comment]
btw, I'm going to come along to Hack the Tower on the 14th November in London. If you come along I can show you roughly where to look to fix some of these niggles that you keep finding. The reality is that we're heavy under resourced, especially in the emacs client side.

**Comment by greenrd** [comment]
OK, I've RSVPed for that - cool!

**Comment by fommil** [comment]
nice! :smile:

**Comment by greenrd** [comment]
Not reproducible. I'll open another one if I see this again.
