### ISSUE TITLE
M-. in indirect buffer kills Ensime

### ISSUE THREAD

**Issue by VlachJosef** [ensime/ensime-emacs#542]
### Steps to reproduce
1. Create file `Main.scala`:

``` scala
package core

object Main {
  def one: String = two
  def two: String = "2"
}
```
1. Run `ensime` command
2. Clone `Main.scala` buffer using `clone-indirect-buffer-other-window` (`C-x 4 c`)
3. Navigate to definition of a method `two` in indirect (cloned) buffer. (ie. `M-.` on line  `def one: String = two`)
### Expected behaviour

Jump to definition of `two` on line `def two: String = "2"`
### Actual behaviour

Ensime is non responsive from now on.

```
16:38:30.157 ERROR akka://ENSIME/user/ensime-main/tcp-server/con1 o.e.s.t.TCPConnectionActor - Error seen during message processing, closing client connection
org.ensime.server.protocol.swank.SwankRPCFormatException: Invalid rpc request (swank:symbol-at-point nil 596)
    at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:860)
    at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:849)
    at org.ensime.sexp.Sexp.convertTo(Sexp.scala:21)
    at org.ensime.server.SwankProtocol.decode(SwankProtocol.scala:17)
    at org.ensime.server.tcp.TCPConnectionActor.repeatedDecode(TCPConnectionActor.scala:108)
    at org.ensime.server.tcp.TCPConnectionActor.attemptProcess(TCPConnectionActor.scala:97)
    at org.ensime.server.tcp.TCPConnectionActor$$anonfun$incoming$1.applyOrElse(TCPConnectionActor.scala:49)
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:467)
    at org.ensime.server.tcp.TCPConnectionActor.aroundReceive(TCPConnectionActor.scala:17)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.ensime.sexp.DeserializationException: Unable to parse SexpNil
    at org.ensime.sexp.formats.package$.deserializationError(package.scala:7)
    at org.ensime.sexp.formats.StandardFormats$$anon$2.read(StandardFormats.scala:50)
    at org.ensime.sexp.formats.StandardFormats$$anon$2.read(StandardFormats.scala:42)
    at org.ensime.sexp.formats.LegacyLowPriorityProductFormats$HListFormat$$anon$4.read(LegacyProductFormats.scala:41)
    at org.ensime.sexp.formats.LegacyLowPriorityProductFormats$HListFormat$$anon$4.read(LegacyProductFormats.scala:35)
    at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$66.read(SwankFormats.scala:661)
    at org.ensime.server.protocol.swank.SwankProtocolRequest$$anon$66.read(SwankFormats.scala:655)
    at org.ensime.sexp.Sexp.convertTo(Sexp.scala:21)
    at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:815)
    at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestFormat$.read(SwankFormats.scala:789)
    at org.ensime.sexp.Sexp.convertTo(Sexp.scala:21)
    at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$41.apply(SwankFormats.scala:854)
    at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$$anonfun$41.apply(SwankFormats.scala:854)
    at scala.util.Try$.apply(Try.scala:192)
    at org.ensime.server.protocol.swank.SwankProtocolRequest$RpcRequestEnvelopeFormat$.read(SwankFormats.scala:854)
    ... 18 common frames omitted
```

...

**Comment by fommil** [comment]
Definitely a client side bug. Should refuse to send the message.

**Comment by fommil** [comment]
sounds like we need to do some investigation to get the underlying buffer file name when in an indirect buffer :disappointed:
