### ISSUE TITLE
ensime-emacs doesn't work with latest helm

### ISSUE THREAD

**Issue by lins05** [ensime/ensime-emacs#592]
Yesterday I upgraded helm to latest github master, then I found ensime server would throws exceptions `Failed to parse sexp` when starting up:

```
<-- (:background-message 105 Initializing Analyzer. Please wait...)
Initializing Analyzer. Please wait...
<-- (:compiler-ready)
ENSIME ready. CanBuildFrom[List[Dream], Reality, List[Reality]]
--> (:swank-rpc (swank:symbol-designations (:file /data/github/spark/spark-master/core/src/main/scala/org/apache/spark/scheduler/SchedulingMode.scala) 0 1125 (var val varField valField functionCall operator param class trait object package implicitConversion implicitParams deprecated)) 2)
<-- (:full-typecheck-finished)
00:17:07.787 ERROR akka://ENSIME/user/ensime-main/tcp-server/con1 o.e.s.t.TCPConnectionActor - Error seen during message processing, closing client connection
java.lang.Exception: Failed to parse sexp: (SexpAtomP | SexpListP | SexpEmptyList | SexpConsP | SexpQuotedP):1:1 ..."(:swank-rp"
	at org.ensime.sexp.SexpParser$.parse(SexpParser.scala:18)
	at org.ensime.sexp.package$EnrichedString$.parseSexp$extension(package.scala:21)
	at org.ensime.server.SwankProtocol.decode(SwankProtocol.scala:17)
	at org.ensime.server.tcp.TCPConnectionActor.repeatedDecode(TCPConnectionActor.scala:108)
	at org.ensime.server.tcp.TCPConnectionActor.attemptProcess(TCPConnectionActor.scala:97)
	at org.ensime.server.tcp.TCPConnectionActor$$anonfun$incoming$1.applyOrElse(TCPConnectionActor.scala:49)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:497)
	at org.ensime.server.tcp.TCPConnectionActor.aroundReceive(TCPConnectionActor.scala:17)
	at akka.actor.ActorCell.
receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
00:17:07.821 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server/con1#1030159971]] terminated
```

## How to reproduce

Using the code of apache spark:

```sh
git clone git://git.apache.org/spark.git
cd spark
./bin/sbt -Phive -Phive-thriftserver -Phadoop-2.6 -Pyarn -Pmesos ensimeConfig
```
Then launch ensime inside emacs.

## FWIW

A few rounds of git-bisecting helped me locate the commit that caused the exception: it is https://github.com/emacs-helm/helm/commit/3a689cc. I reverted the commit on top of the latest master -- and it fixed the above error :)

**Comment by fommil** [comment]
I have absolutely no idea how helm managed to cause a regression in ensime, but thanks for bisecting to find this out! Should we close this since it's a bug in helm?

**Comment by lins05** [comment]
SGTM. I justed wanted to post it here so others who encounter the same problem could find it.

**Comment by yangwen0228** [comment]
Yes, I encountered this problem also. And if we close a file and use helm to open that file again, it can lead to this problem, too. 

[Workaround] We can use `projectile-kill-buffers` to close all the buffers related to the project, then run `ensime` to start the server again, it works! Or restart Emacs can solve this problem.
